spec:                                                                                                                                                                                                                                                                                                              
  template:
    spec:
      volumes:
        - name: experiment-data
          hostPath:
            path: /mnt/data/detection-experiments
            type: DirectoryOrCreate
      containers:
        - name: app
          volumeMounts:
            - mountPath: /data
              name: experiment-data
              subPath: detection2  # unique subdir per app
